### PR TITLE
Implement scale factors for ICARTT files

### PR DESCRIPTION
**Pull request by cdholmes**
This feature seems to work without any problems.

### CODE REVIEW

**Comment by cdholmes** [comment]
I don't think that the type checking the scale factors is required here. If there are fewer scale factors (for LOD flags) than variables, then an error will occur later in the program when the scale factors and flags are associated with variables. If some of the scale factors are not numeric type, that will similarly cause an error at that time. The user should get errors, not silent bad data.

**Comment by barronh** [comment]
Thanks for looking into this. 

Certainly scaling without error checking is good. It would also be nice to do some checking here because the subsequent error may not be obvious to the users. 

Also, have you tried saving to NetCDF and then reading from the NetCDF file? Is the scale factor getting stored in a scale_factor property so that it is correctly applied during storage?

**Comment by barronh** [comment]
p.s., would check myself but my work computer is down. Respond on my phone.

**Comment by cdholmes** [comment]
I generated a netcdf file with pncgen at the command line and there is indeed an issue there. The “scale_factor” attribute is stored in the netcdf file, but the stored values have not been transformed consistent with that scale factor. In other words, the scale factor is applied once by pncgen when it creates the netcdf file and the scale factor will applied again a second time when the netcdf file is read in, leading to incorrect values.

I guess that means that pnc was correctly generating netcdf files BEFORE by bug fix even though pnc incorrectly read the data.

Chris

**Comment by cdholmes** [comment]
This pull request now incorporates the fix mentioned in my last comment. The scale factors are set to 1 after applying them to the variable. I verified that the netcdf file generated by pncgen is read correctly by other programs (no further scaling needed) AND pncopen correctly reads the data in python.

**Comment by cdholmes** [comment]
I implemented the fix mentioned in my last comment. Scale factors are set to 1 after applying to the variable, so that no further scaling is applied in python or netcdf files that are generated. I verified that pncopen returns correct variable values in python and pncgen creates netcdf files that are correctly read by other programs.

**Comment by barronh** [comment]
@cdholmes 

The current failure seems unrelated to your update.  I'll figure out the next step. It looks like a netcdf4 python library version 1.5.3 issue -- maybe specific to the build platform...

**Comment by barronh** [comment]
I restarted the build and it worked, so we're all good. For another time, we might want to test renaming scale to scale_factor and see if we can not reset.  For now, merging. Thanks for the addition!

**Pull request merged**
